on:
  pull_request:
  push:
    branches: [main]
    
name: CI

jobs:
  stack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10']
        cabal: [latest]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: CI ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: 'latest'      
      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test --system-ghc
